# Generated by Django 3.2.13 on 2022-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='accuracy_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
