# Generated by Django 3.2.13 on 2022-06-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_alter_telegramuser_options'),
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramuser'),
        ),
    ]
