# Generated by Django 3.2.13 on 2022-06-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_auto_20220609_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_randomized_data_only', 'Can view randomized data only'), ('can_view_all_data', 'Can view all data')]},
        ),
    ]
