# Generated by Django 3.2.13 on 2022-06-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0005_alter_geolocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='heading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
