# Generated by Django 3.2.13 on 2022-06-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geolocations', '0006_auto_20220612_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
