---
- name: "Restart {{ app_name }} app"
  listen: Restart app 
  become: yes
  service:
    name: "{{ app_name }}"
    state: restarted
    daemon-reload: yes
  when: not ansible_check_mode

# vim: ai et ts=2 sw=2 sts=2 nu
