---
- name: create database
  mysql_db:
    config_file: /opt/bitnami/mariadb/conf/my.cnf
    state: present
    name: "{{ mariadb_name }}"
    collation: utf8_bin
    encoding: utf8
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"
    login_user: root

- name: Create user with password, all database privileges and WITH GRANT OPTION for each app
  community.mysql.mysql_user:
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"
    login_user: root
    state: present
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_name }}.*:ALL,GRANT"


- name: Create db backup directory
  become: yes
  file:
    path: '/opt/bitnami/apps/db_backups'
    owner: bitnami
    group: bitnami
    mode: 0755
    state: directory

- name: create cronjob to backup database
  cron:
    name: "{{ mariadb_name }} database backup"
    hour: "{{ db_backup_cron_hour }}"
    minute: "{{ db_backup_cron_min }}"
    weekday: "{{ db_backup_cron_weekday }}"
    day: "{{ db_backup_cron_day }}"
    job: "(/opt/bitnami/mariadb/bin/mysqldump -u '{{ mariadb_user | regex_replace('%', '\\%') }}'  --password='{{ mariadb_password | regex_replace('%', '\\%') }}' '{{ mariadb_name }}' | gzip  > /opt/bitnami/apps/db_backups/{{ mariadb_name | regex_replace('%', '_') }}.backup.$(date +\\%d).sql.gz) 2>/dev/null"
    state: present
    disabled: "{{ db_backup_cron_disable }}"

- name: install required apt packages for django
  become: yes
  apt:
    pkg:
    - python3-dev
    - default-libmysqlclient-dev
    - build-essential
    update_cache: yes
    autoclean: yes
    autoremove: yes

# vim: ai et ts=2 sw=2 sts=2 nu
