# Generated by Django 3.2.13 on 2022-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='user_id')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='username')),
                ('randomized_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='randomized id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
