# Generated by Django 3.2.13 on 2022-06-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['created_at']},
        ),
    ]
