# Generated by Django 3.2.13 on 2022-05-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUsers',
            new_name='TelegramUser',
        ),
    ]
