# Generated by Django 3.2.13 on 2022-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='user_id'),
        ),
    ]
