# Generated by Django 3.2.13 on 2022-05-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_rename_telegramusers_telegramuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='name',
            new_name='username',
        ),
    ]
