# Generated by Django 3.2.13 on 2022-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='user_id'),
        ),
    ]
