# Generated by Django 3.2.13 on 2022-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_auto_20220527_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='randomized_id',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='randomized id'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
