---
- name: remove default wp database
  mysql_db:
    config_file: /opt/bitnami/mariadb/conf/my.cnf
    state: absent
    name: "{{ item }}"
    collation: utf8_bin
    encoding: utf8
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"
    login_user: root
  loop: 
    - bitnami_wordpress
    - test

- name: remove unnecessary users
  community.mysql.mysql_user:
    config_file: /opt/bitnami/mariadb/conf/my.cnf
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"
    login_user: root
    state: absent
    name: "{{ item }}"
    host_all: true
  loop:
    - bn_wordpress

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    config_file: /opt/bitnami/mariadb/conf/my.cnf
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"
    login_user: root
    name: ''
    host_all: yes
    state: absent

# vim: ai et ts=2 sw=2 sts=2 nu
