---
- hosts: nginx_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    HOME: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - "{{ lookup('env', 'PATH_TO_PRIVATE_VARS_YAML') }}"
  connection: local
  roles:
    - role: optional_prep_work
      tags: [optional_prep_work]
    - role: remove_default_wordpress
      tags: [remove_default_wordpress]
    - role: mariadb_setup
      tags: [mariadb_setup]
    - role: geolocation_restapi
      tags: [geolocation_restapi]

# vim: ai et ts=2 sw=2 sts=2 nu
