---
- hosts: nginx_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    HOME: "{{ lookup('env', 'HOME') }}"
  vars_files:
    #- /opt/bitnami/apps/configuration/list_uptimes_private_vars.yaml
    - "{{ lookup('env', 'PATH_TO_PRIVATE_VARS_YAML') }}"
  connection: local
  roles:
    - role: optional_prep_work
      tags: [optional_prep_work]
    - role: list_uptimes
      tags: [list_uptimes]

# vim: ai et ts=2 sw=2 sts=2 nu
