---
#Comments:
#    ansible-galaxy collection install community.postgresql --upgrade to get to 2.1.5
#    run --tags postgres_initial_play first

- hosts: nginx_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    HOME: "{{ lookup('env', 'HOME') }}"
    db_name: "{{ postgres_db_name | default('boohoo', true) }}"
    db_user: "{{ postgres_db_user | default('woohoo', true) }}"
    db_password: "{{ postgres_db_password | default('yoohoo', true) }}"
  connection: local
  roles:
    - role: postgres
      tags: [postgres]

# In development
#  vars_files:
#    - "{{ lookup('env', 'PATH_TO_PRIVATE_VARS_YAML') }}"
# vim: ai et ts=2 sw=2 sts=2 nu
