---
HOSTNAME: value
local_timezone: 'America/New_York'

app_name: 'location_app'
python_version: 'python3.7'

PATH_TO_PYTHON: '/opt/bitnami/apps/location_app/venv/bin/python'
LIVE_APP_SCRIPT: 'location_app.py'

TOKEN_LOCATION_BOT: 'token_for_location_app_bot'
API_ID: 'api_id'
API_HASH: 'api_hash'

RSYNC_EXCLUDES:
  - "--exclude Pip*"
  - "--exclude Readme.md"
  - "--exclude .env"
  - "--exclude list_uptimes.py"
  - "--exclude location_to_restapi_app.py"
  - "--exclude post_to_restapi.py"
  - "--exclude telethon_utils_v2.py"

# vim: ai et ts=2 sw=2 sts=2 nu
